---
resources:
- name: graphql-client
  type: git
  icon: github
  source:
    uri: https://github.com/hamidval/graphql-client.git

- name: node-image
  type: registry-image
  source:
    repository: node
    tag: 18

jobs:
- name: graphql-client
  trigger: true
  public: true
  plan:
  - get: node-image
  - get: graphql-client
    trigger: true
  - task: install
    image: node-image
    config:
      inputs:
      - name: graphql-client
      outputs:
      - name: dependencies
        path: graphql-client/node_modules
      platform: linux
      run:
        path: npm
        args: ["install"]
        dir: graphql-client
  - task: build
    image: node-image
    config:
      inputs:
      - name: graphql-client
      outputs:
      - name: dependencies
        path: graphql-client/node_modules
      platform: linux
      run:
        path: npm
        args: ["run", "build"]
        dir: graphql-client
  - task: test
    image: node-image
    config:
      inputs:
      - name: graphql-client
      - name: dependencies
        path: graphql-client/node_modules
      platform: linux
      run:
        path: npm
        args: ["run", "test"]
        dir: graphql-client